#!/bin/bash
#
#Create a git server... 
# Create the instance
#
. settings.conf

#create group 
# ec2-create-group $GROUP -d "Security group for git server" --region $REGION
# ec2-authorize-group $GROUP -P tcp -p 80 --region $REGION
# ec2-authorize-group $GROUP -P tcp -p 443 --region $REGION
# ec2-authorize-group $GROUP -P tcp -p 22 --region $REGION
# ec2-authorize-group $GROUP -P tcp -p 9418 --region $REGION

#launch instance from AMI
INSTANCE=`ec2-run-instances ami-83cd5eb9 -n 1 -k $KEY --instance-type t1.micro -g $GROUP --region $REGION -z $ZONE | grep INSTANCE | awk '{print $2}'`
echo "run instance : ${INSTANCE}"

# Name the instance in the AWS EC2 console
ec2-create-tags ${INSTANCE} -t Name=${NAME} --region ${REGION}
